
# 数据库访问配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.201.10:1521:jjgl
    username: EI
    password: JSJC_EI
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 20
    minIdle: 20
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #redis基础配置#
  redis:
    database: 0
    host: 192.168.202.12
    password: Founder123
    port: 6379
    timeout: 3000 # 连接超时时间 单位 ms（毫秒）
    #redis线程池设置#
    pool:
      max-idle: 500 # 连接池中的最大空闲连接，默认值也是8。
      min-idle: 50  #连接池中的最小空闲连接，默认值也是0。
      max-active: 2000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      #redis负载设置#################
      #sentinel:
      # Redis服务器master的名字
      #master: master01
      # redis-sentinel的配置地址和端口
      #nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378

  #dubbo配置
  dubbo:
    application:
      name: ei-web
    registry:
      protocol: zookeeper
      address: 192.168.202.12:2181
      check: false

fileUpload:
  filePath: /data/fileupload
  filePathRelative: /ei/
  fileAddr: http://192.168.202.11:11808/



