
# 数据库访问配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.201.10:1521:jjgl
    username: EI
    password: JSJC_EI
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 20
    minIdle: 20
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  #dubbo配置
  dubbo:
    server: true
    application:
      name: ei-service
    registry:
      protocol: zookeeper
      address: 192.168.202.12:2181
      check: false
    protocol:
      name: dubbo
      port: 20882

uim:
  appId: 10001
  outRoles:
    fundMA: 1005001
    fundMC: 1005002
    bank: 1005003



